export const copy = {
  title: "فلك",
  latin: "FALAK",
  tagline: "موجات من الأعماق. أطلق، ترقَّ، ابقَ على قيد الحياة.",
  start: "ابدأ",
  scores: "أعلى النتائج",
  howMove: "الحركة",
  howMoveHint: "WASD أو الأسهم — أو حرّك المؤشر",
  howAim: "التصويب",
  howAimHint: "اتجاه المؤشر، أو أقرب عدو على اللمس",
  howFire: "الإطلاق",
  howFireHint: "مسافة أو نقرة. استمر للرمي الآلي",
  howPause: "إيقاف",
  howPauseHint: "Esc أو زر الإيقاف",
  pause: "إيقاف مؤقت",
  resume: "استئناف",
  restart: "إعادة",
  menu: "القائمة",
  gameover: "انتهت الرحلة",
  wave: "موجة",
  score: "النقاط",
  lives: "المحاولات",
  combo: "سلسلة",
  enterName: "اسم القائد",
  saveScore: "حفظ النتيجة",
  skipSave: "تخطي",
  emptyScores: "لا نتائج بعد — كن الأول.",
  back: "رجوع",
  upgradeTitle: "اختر ترقية",
  spread: "إطلاق متعدد",
  spreadHint: "مقذوفات إضافية في مروحة أوسع",
  shield: "درع",
  shieldHint: "طبقة حماية تمتص ضربة وتعيد الشحن",
  speed: "سرعة",
  speedHint: "استجابة أعلى واندفاع أسرع",
  muted: "كتم",
  shake: "اهتزاز",
  follow: "اتباع المؤشر",
  waveClear: "الموجة اكتملت",
  waveStart: (n: number) => `الموجة ${n}`,
  maxed: "الحد الأقصى",
  you: "نتيجتك",
} as const;
